
DELETE  https://636b3a947f47ef51e12abb5f.mockapi.io/product_data/

###
GET https://636b3a947f47ef51e12abb5f.mockapi.io/product_data/3
Content-Type: application/json

{
  "name":"aman",
  "image":[1,2,3]
}

###
https://63985bc3044fa481d69a6daf.mockapi.io/Lipstic